routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//BACKEND
Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'middleware' => 'auth'], function () {
    Route::get('', 'IndexController@index');
    Route::resource('users', 'UserController')->middleware('role:superAdmin|admin');
    Route::get('/users/pagination/fetch_data', 'UserController@fetchData')->name('users.fetch_data');
    Route::group(['prefix' => 'tasks'], function () {
        Route::post('change_status/{id}', 'TaskController@changeStatus')->name('task.status');
        Route::post('content/{id}', 'TaskController@updateContent')->name('task.content');
        Route::get('pagination/fetch_data', 'TaskController@fetchData')->name('tasks.fetch_data');
        Route::get('/charts', 'TaskController@doChart')->middleware('permission:edit-user|delete-user');
    });
    Route::resource('tasks', 'TaskController');
    Route::resource('statuses', 'StatusController');
    Route::resource('categories', 'CategoryController');
    Route::get('/categories/pagination/fetch_data', 'CategoryController@fetchData')->name('category.fetchData');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/API/TaskController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskAddRequest;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        return response()->json([
            'statusCode'    =>  200,
            'data'          =>  $tasks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskAddRequest $request)
    {
        //add task
        $task = new Task;
        $task->name = $request->task_name;
        $task->statusid = $request->status;
        $task->save();

        // add staff of that task
        $mang=array();
        foreach ($request->user as $value) {
            $mang[]=$value;
        }
        $task->user()->Attach($mang);

        return response()->json([
            'status'    =>  'success',
            'message'   =>  'Thêm công việc thành công'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $task
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/API/UserController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Http\Response;
use App\Http\Requests\{UserAddRequest,UserEditRequest};

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function index()
    {
        $users = User::all();
        return response()->json([
            'status' => '200',
            'data'   => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(UserAddRequest $request)
    {
        $request_data = $request->all();
        $request_data['password'] = bcrypt($request->input['password']);
        return User::create($request_data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $user
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findorfail($id);
        $request_data = $request->all();
        if(isset($request_data['password'])){
            $request_data['password'] = ($request_data['password']=="")?$user->password:bcrypt($request->input('password'));
        }
        $user->update($request_data);
        return response()->json([
            'status'    => 200,
            'message'   => 'Update user successfully',
            'data'      =>  $user
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json([
            'status'    =>  204,
            'message'   =>  'Delete user successfully'
        ]);
    }
}

app/Http/Controllers/Backend/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\{CategoryAddRequest, CategoryEditRequest};
use Illuminate\View\View;

class CategoryController extends Controller
{
    protected $category;

    /**
     * CategoryController constructor.
     * @param $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryAddRequest $request
     * @return JsonResponse
     */
    public function store(CategoryAddRequest $request)
    {
        $requestData = $request->all();
        $this->category->saveCategory($requestData);
        return response()->json([
            'message' => 'Thêm danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $category = $this->category->findOrFail($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryEditRequest $request
     * @param int $id
     * @return JsonResponse
     */
    public function update(CategoryEditRequest $request, $id)
    {
        $requestData = $request->all();
        $this->category->updateCategory($requestData, $id);
        return response()->json([
            'message' => 'Sửa danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     */
    public function destroy($id)
    {
        $category = $this->category->deleteCategory($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $category->id
        ]);
    }

    public function fetchData(Request $request)
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }

    public function reloadCategory()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }
}

app/Http/Controllers/Backend/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index(){
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/Admin/StatusController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return void
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use App\Models\Status;
use App\Models\Task;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\View\View;
use App\Http\Requests\{TaskAddRequest, TaskEditRequest};
use Illuminate\Support\Facades\Auth;
use Throwable;

class TaskController extends Controller
{
    protected $user;
    protected $task;
    protected $status;

    /**
     * TaskController constructor.
     * @param Task $task
     * @param User $user
     * @param Status $status
     */
    public function __construct(Task $task, User $user, Status $status)
    {
        $this->task = $task;
        $this->user = $user;
        $this->status = $status;
    }

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.index', compact('users', 'tasks', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param TaskAddRequest $request
     * @return array|string
     * @throws Throwable
     */
    public function store(TaskAddRequest $request)
    {
        $requestData = $request->all();
        $task = $this->task->saveTask($requestData);
        return response()->json([
            'urlTask' => route('tasks.show', $task->id),
            'message' => 'Thêm công việc thành công',
            'data' => $this->reloadTask()
        ]);

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $task = $this->task->findOrFail($id);
        return view('backend.task.content', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $task = $this->task->findOrFail($id);
        $status = $this->status->all();
        $users = $this->user->getAll();
        return view('backend.task.edit', compact('users', 'task', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param TaskEditRequest $request
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function update(TaskEditRequest $request, $id)
    {
        $requestData = $request->all();
        $task = $this->task->updateTask($requestData, $id);
        return response()->json([
            'id' => $task->id,
            'message' => 'Cập nhật công việc thành công',
            'data' => $this->reloadTask(),
            'urlTask' => route('tasks.show', $task->id)
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     * @throws Throwable
     */
    public function updateContent(Request $request, $id)
    {
        $this->task->updateContent($request->all(), $id);
        return response()->json([
            'message' => 'Cập nhật thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function destroy($id)
    {
        $task = $this->task->deleteTask($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $task->id
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return array|string
     * @throws Throwable
     */
    public function changeStatus(Request $request, $id)
    {
        $requestData = $request->all();
        $this->task->changeStatus($requestData, $id);
        return response()->json([
            'message' => 'Cập nhật trạng thái thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * @param Request $request
     * @return array|string
     * @throws Throwable
     */
    public function fetchData(Request $request)
    {
        $users = $this->user->getAll();
        $status = $this->status->all();
        $txtSearch = str_replace(" ", "%", $request->get('txtSearch'));
        $tasks = $this->task->getTaskByQuery($txtSearch, 5);
        if ($tasks->count() > 0) {
            return view('backend.task.data_body', compact('users', 'status', 'tasks'))->render();
        } else {
            return "Không tìm thấy kết quả";
        }
    }

    /**
     * @return Application|Factory|View
     */
    public function doChart()
    {
        return view('backend.task.chart');
    }

    /**
     * @return array|string
     * @throws Throwable
     */
    public function reloadTask()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.data_body', compact('users', 'tasks', 'status'))->render();
    }
}

resources/views/backend/category/data_body.blade.php
@foreach ($categories as $category)
    <tr class="odd gradeX" id="category{{$category->id}}" align="center">
        <td>{{$category->id}}</td>
        <td>{{$category->name}}</td>
        <td>{{$category->slug}}</td>
        <td class="center"><i class="fa fa-pencil fa-fw btn-edit" data-target="#editCategoryModal" data-toggle="modal"
                              data-id="{{$category->id}}" data-action="{{route('categories.edit',$category->id)}}"></i>
        </td>
        <td class="center"><i class="fa fa-trash-o fa-fw btn-delete"
                              data-action="{{ route('categories.destroy',$category->id) }}"></i></td>
    </tr>
@endforeach
<tr>
    <td colspan="5">
        {{$categories->links()}}
    </td>
</tr>

resources/views/backend/category/edit.blade.php
<div class="modal-header">
    <h4 class="modal-title">Sửa danh mục #{{$category->id}}</h4>
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<form method="post" id="updateCategoryForm">
    @csrf
    <input type="hidden" name="hidden_id" class="form-control" value="{{ $category->id }}">
    <div id="form-result"></div>
    <div class="modal-body">
        <div class="form-group">
            <label for="">Tiêu đề</label>
            <input type="text" name="name" class="form-control" value="{{ $category->name }}">
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info pull-right" id="btn-update-category"
                data-action="{!! route('categories.update',$category->id) !!}">Lưu lại
        </button>
        <button type="button" class="btn btn-dark" data-dismiss="modal">Đóng</button>
    </div>
</form>
<!--end-add-category-->

resources/views/backend/category/index.blade.php
@extends('backend.master.master')
@section('title','Category Management')
@section('content')
    <!-- Page Content -->
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Thể loại
                    </h1>
                </div>
                <div class="col-lg-12">
                    @if (session('thongbao'))
                        <div class="alert alert-success" role="alert">
                            <strong>{{session('thongbao')}}</strong>
                        </div>
                    @endif
                </div>
                <div class="col-md-3 col-md-push-9">
                    <button type="button" class="btn btn-info btn-show-add" data-toggle="modal"
                            data-target="#addCategoryModal">Thêm thể loại
                    </button>
                </div>
                <!--Add category-->
                <div id="addCategoryModal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Thêm danh mục</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>
                            <form method="post" id="addCategoryForm">
                                @csrf
                                <div id="form_result"></div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="">Tiêu đề</label>
                                        <input type="text" name="name" class="form-control"
                                               placeholder="Mời nhập tiêu đề">
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-info pull-right" id="btn-add-category"
                                            data-action="{{route('categories.store')}}">Lưu lại
                                    </button>
                                    <button type="button" class="btn btn-dark" data-dismiss="modal">Đóng</button>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
                <!--end-add-category-->

                <!--Edit category-->
                <div id="editCategoryModal" class="modal fade" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">

                        </div>
                    </div>
                </div>
                <!--end-add-category-->
                <!-- /.col-lg-12 -->
                <table class="table table-striped table-bordered table-hover" id="category_table">
                    <thead>
                    <tr align="center">
                        <th>#</th>
                        <th>Tên</th>
                        <th>Tên không dấu</th>
                        <th>Sửa</th>
                        <th>Xóa</th>
                    </tr>
                    </thead>
                    <tbody>
                    @include('backend.category.data_body')
                    </tbody>
                </table>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
    <!-- /#page-wrapper -->
@endsection

@section('script')
    @parent
    <script src="js/backend/ajax/category.js"></script>
@endsection