routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//BACKEND
Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'middleware' => 'auth'], function () {
    Route::get('', 'IndexController@index');
    Route::resource('users', 'UserController')->middleware('role:superAdmin|admin');
    Route::get('/users/pagination/fetch_data', 'UserController@fetchData')->name('users.fetch_data');
    Route::group(['prefix' => 'tasks'], function () {
        Route::post('change_status/{id}', 'TaskController@changeStatus')->name('task.status');
        Route::post('content/{id}', 'TaskController@updateContent')->name('task.content');
        Route::get('pagination/fetch_data', 'TaskController@fetchData')->name('tasks.fetch_data');
        Route::get('/charts', 'TaskController@doChart')->middleware('permission:edit-user|delete-user');
    });
    Route::resource('tasks', 'TaskController');
    Route::resource('statuses', 'StatusController');
    Route::resource('categories', 'CategoryController');
    Route::get('/categories/pagination/fetch_data', 'CategoryController@fetchData')->name('category.fetchData');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/API/TaskController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskAddRequest;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        return response()->json([
            'statusCode'    =>  200,
            'data'          =>  $tasks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskAddRequest $request)
    {
        //add task
        $task = new Task;
        $task->name = $request->task_name;
        $task->statusid = $request->status;
        $task->save();

        // add staff of that task
        $mang=array();
        foreach ($request->user as $value) {
            $mang[]=$value;
        }
        $task->user()->Attach($mang);

        return response()->json([
            'status'    =>  'success',
            'message'   =>  'Thêm công việc thành công'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $task
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/API/UserController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Http\Response;
use App\Http\Requests\{UserAddRequest,UserEditRequest};

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function index()
    {
        $users = User::all();
        return response()->json([
            'status' => '200',
            'data'   => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(UserAddRequest $request)
    {
        $request_data = $request->all();
        $request_data['password'] = bcrypt($request->input['password']);
        return User::create($request_data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $user
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findorfail($id);
        $request_data = $request->all();
        if(isset($request_data['password'])){
            $request_data['password'] = ($request_data['password']=="")?$user->password:bcrypt($request->input('password'));
        }
        $user->update($request_data);
        return response()->json([
            'status'    => 200,
            'message'   => 'Update user successfully',
            'data'      =>  $user
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json([
            'status'    =>  204,
            'message'   =>  'Delete user successfully'
        ]);
    }
}

app/Http/Controllers/Backend/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\{CategoryAddRequest, CategoryEditRequest};
use Illuminate\View\View;

class CategoryController extends Controller
{
    protected $category;

    /**
     * CategoryController constructor.
     * @param $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryAddRequest $request
     * @return JsonResponse
     */
    public function store(CategoryAddRequest $request)
    {
        $requestData = $request->all();
        $this->category->saveCategory($requestData);
        return response()->json([
            'message' => 'Thêm danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $category = $this->category->findOrFail($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryEditRequest $request
     * @param int $id
     * @return JsonResponse
     */
    public function update(CategoryEditRequest $request, $id)
    {
        $requestData = $request->all();
        $this->category->updateCategory($requestData, $id);
        return response()->json([
            'message' => 'Sửa danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     */
    public function destroy($id)
    {
        $category = $this->category->deleteCategory($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $category->id
        ]);
    }

    public function fetchData(Request $request)
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }

    public function reloadCategory()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }
}

app/Http/Controllers/Backend/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index(){
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/Admin/StatusController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return void
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use App\Models\Status;
use App\Models\Task;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\View\View;
use App\Http\Requests\{TaskAddRequest, TaskEditRequest};
use Illuminate\Support\Facades\Auth;
use Throwable;

class TaskController extends Controller
{
    protected $user;
    protected $task;
    protected $status;

    /**
     * TaskController constructor.
     * @param Task $task
     * @param User $user
     * @param Status $status
     */
    public function __construct(Task $task, User $user, Status $status)
    {
        $this->task = $task;
        $this->user = $user;
        $this->status = $status;
    }

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.index', compact('users', 'tasks', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param TaskAddRequest $request
     * @return array|string
     * @throws Throwable
     */
    public function store(TaskAddRequest $request)
    {
        $requestData = $request->all();
        $task = $this->task->saveTask($requestData);
        return response()->json([
            'urlTask' => route('tasks.show', $task->id),
            'message' => 'Thêm công việc thành công',
            'data' => $this->reloadTask()
        ]);

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $task = $this->task->findOrFail($id);
        return view('backend.task.content', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $task = $this->task->findOrFail($id);
        $status = $this->status->all();
        $users = $this->user->getAll();
        return view('backend.task.edit', compact('users', 'task', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param TaskEditRequest $request
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function update(TaskEditRequest $request, $id)
    {
        $requestData = $request->all();
        $task = $this->task->updateTask($requestData, $id);
        return response()->json([
            'id' => $task->id,
            'message' => 'Cập nhật công việc thành công',
            'data' => $this->reloadTask(),
            'urlTask' => route('tasks.show', $task->id)
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     * @throws Throwable
     */
    public function updateContent(Request $request, $id)
    {
        $this->task->updateContent($request->all(), $id);
        return response()->json([
            'message' => 'Cập nhật thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function destroy($id)
    {
        $task = $this->task->deleteTask($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $task->id
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return array|string
     * @throws Throwable
     */
    public function changeStatus(Request $request, $id)
    {
        $requestData = $request->all();
        $this->task->changeStatus($requestData, $id);
        return response()->json([
            'message' => 'Cập nhật trạng thái thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * @param Request $request
     * @return array|string
     * @throws Throwable
     */
    public function fetchData(Request $request)
    {
        $users = $this->user->getAll();
        $status = $this->status->all();
        $txtSearch = str_replace(" ", "%", $request->get('txtSearch'));
        $tasks = $this->task->getTaskByQuery($txtSearch, 5);
        if ($tasks->count() > 0) {
            return view('backend.task.data_body', compact('users', 'status', 'tasks'))->render();
        } else {
            return "Không tìm thấy kết quả";
        }
    }

    /**
     * @return Application|Factory|View
     */
    public function doChart()
    {
        return view('backend.task.chart');
    }

    /**
     * @return array|string
     * @throws Throwable
     */
    public function reloadTask()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.data_body', compact('users', 'tasks', 'status'))->render();
    }
}

resources/views/backend/task/chart.blade.php
@extends('backend.master.master')
@section('title','Task Chart')
@section('content')
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Biểu đồ công việc</h3>
            </div>

            <div class="title_right">
                <div class="col-md-5 col-sm-5   form-group pull-right top_search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-6 col-sm-6  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Pie Graph Chart <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <canvas id="pieChart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Donut Graph <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="#">Settings 1</a>
                                    <a class="dropdown-item" href="#">Settings 2</a>
                                </div>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <canvas id="canvasDoughnut"></canvas>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
@endsection

@section('script')
@parent
<!-- Chart.js -->
<script src="vendors/Chart.js/dist/Chart.js"></script>
@endsection

resources/views/backend/task/data_body.blade.php
@foreach ($tasks as $task)    <div id="form-result"></div>
    <tr id="task{{$task->id}}">
        <td>{{$task->id}}</td>
        <td class="task-name">{{$task->name}}</td>
        <td class="task-user">
            @foreach ($task->users as $user)
                <button type="button" class="btn btn-info btn-show-staff" data-id="{{$user->id}}"
                        data-target="">{{$user->name}}</button>
            @endforeach
        </td>
        <td>
            {{Carbon\Carbon::parse($task->created_at)->format('H:m:s d-m-Y')}}
        </td>
        <td>
            <select class="browser-default custom-select slt_status
                    @if($task->status->id==1){{"to-do"}}
            @elseif($task->status->id==2){{"doing"}}
            @elseif($task->status->id==3){{"checking"}}
            @elseif($task->status->id==4){{"confirm"}}
            @elseif($task->status->id==5){{"done"}}
            @endif"
                    data-id="{{$task->id}}" data-action="{{URL('/admin/tasks/change_status',['task_id'=>$task->id])}}">
                @foreach($status as $item)
                    <option value="{{$item->id}}"
                    @if($item->id==$task->status->id)
                        {{"selected"}}
                        @endif
                    >
                        {{$item->name}}
                    </option>

                @endforeach

            </select>
        </td>
        <td>
            <button class="btn btn-primary btn-show" data-action="{{ route('tasks.show',$task->id) }}">
                <i class="fa fa-eye" title="Xem"></i>
            </button>
            <button class="btn btn-warning btn-edit-task" data-action="{{route('tasks.edit',$task->id)}}"
                    data-toggle="modal" data-target="#editTaskModal" data-id="{{$task->id}}">
                <i class="fa fa-edit" title="Sửa"></i>
            </button>
            <button class="btn btn-danger btn-del-task" data-action="{{route('tasks.destroy',$task->id)}}">
                <i class="fa fa-remove" title="Xóa"></i>
            </button>
        </td>
    </tr>
@endforeach
<tr>
    <td colspan="6" align="center">
        {{$tasks->links()}}
    </td>
</tr>

resources/views/backend/task/edit.blade.php
<form action="{{route('tasks.update',$task->id)}}" method="post" id="editTaskForm">
    @method('PUT')
    @csrf
    <div id="form_result"></div>
    <div class="modal-body">
        <input type="hidden" name="task_id" value="{{$task->id}}">
        <div class="form-group">
            <label for="">Tiêu đề</label>
            <input type="text" name="name" class="form-control"
                   placeholder="Mời nhập tiêu đề" value="{{$task->name}}">
        </div>
        <div class="form-group">
            <label for="">Người phụ trách</label><br>
            <div class="form-group" style="margin: 0 10px;">
                @foreach ($users as $user)
                    <input type="checkbox" id="chb_{{$user->id}}" name="user[]" value="{{$user->id}}"
                    @foreach($task->users as $item)
                        @if($user->id == $item->id)
                            {{"checked"}}
                            @endif
                        @endforeach
                    >
                    <label for="chb_{{$user->id}}" style="cursor: pointer">{{$user->name}}</label>
                    <br>
                @endforeach
            </div>
        </div>
        <div class="form-group">
            <label for="">Trạng thái</label>
            <select class="form-control" name="status" id="">
                @foreach ($status as $item)
                    <option value="{{$item->id}}"
                    @if($item->id == $task->status->id)task_management
                        {{"selected"}}
                        @endif
                    >{{$item->name}}</option>
                @endforeach

            </select>
        </div>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-info pull-right edit-task" id="btn-update-task"
                data-action="{{route('tasks.update',$task->id)}}">Lưu lại
        </button>
        <button type="button" class="btn btn-dark" data-dismiss="modal">Đóng</button>
    </div>
</form>

resources/views/backend/task/index.blade.php
@extends('backend.master.master')
@section('css')
    @parent
    <link rel="stylesheet" href="css/task.css">
@endsection
@section('title','Task Management')
@section('content')
    <h1 class="text-center">Danh sách công việc</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-md-push-9">
                <button type="button" class="btn btn-info btn-add" data-toggle="modal" data-target="#addTaskModal">Thêm
                    công việc
                </button>
            </div>
            <div class="col-md-9">
                <form data-action="{{ route('tasks.fetch_data') }}" method="get" id="fetchDataForm"
                      style="width: 100%">
                    <input type="text" name="txt_search" id="txt_search"
                           style="float: right;border-radius: 5px;padding: 5px;"
                           placeholder="Tìm kiếm....">
                </form>
            </div>
        </div>

        <div class="panel panel-success table-responsive">
            <table class="table table-hover table-striped" id="task_table">
                <thead>
                <tr class="table-info">
                    <th>#</th>
                    <th>Công việc</th>
                    <th>Nhân viên phụ trách</th>
                    <th>Ngày bắt đầu</th>
                    <th>Trạng thái</th>
                    <th>Tùy chọn</th>
                </tr>
                </thead>
                <tbody>
                @include('backend.task.data_body')
                </tbody>

            </table>
            <input type="hidden" name="hidden_page" id="hidden_page" value="1"/>
        </div>
        <!-- Add Task Modal -->
        <div id="addTaskModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div id="form-result"></div>
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Thêm công việc</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <form action="{{route('tasks.store')}}" method="post" id="taskForm">
                        @csrf
                        <div id="form_result"></div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="">Tiêu đề</label>
                                <input type="text" name="name" class="form-control"
                                       placeholder="Mời nhập tiêu đề">

                            </div>
                            <div class="form-group">
                                <label for="">Người phụ trách</label>
                                <br>
                                <div class="form-group" style="margin: 0 10px;">
                                    @foreach ($users as $user)
                                        <input type="checkbox" id="chb_{{$user->id}}" name="user[]"
                                               value="{{$user->id}}">
                                        <label for="chb_{{$user->id}}" style="cursor: pointer">{{$user->name}}</label>
                                        <br>
                                    @endforeach
                                </div>

                            </div>
                            <div class="form-group">
                                <label for="">Trạng thái</label>
                                <select class="form-control" name="status_id" id="">
                                    @foreach ($status as $item)
                                        <option value="{{$item->id}}">{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-info pull-right" id="btn-add-task"
                                    data-action="{!! route('tasks.store') !!}">Lưu lại
                            </button>
                            <button type="button" class="btn btn-dark" data-dismiss="modal">Đóng</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

        <!--Add Content Task-->
        <div class="modal fade" id="contentTask" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content" style="width: 130%;">

                </div>
            </div>
        </div>
        <!--End-->


        <!--Edit Task Modal-->
        <div id="editTaskModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Sửa công việc</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-content2">
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('script')
    @parent
    <script src="js/backend/ajax/task.js"></script>
@endsection