routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//BACKEND
Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix' => 'admin', 'namespace' => 'Backend\Admin', 'middleware' => 'auth'], function () {
    Route::get('', 'IndexController@index');
    Route::resource('users', 'UserController')->middleware('role:superAdmin|admin');
    Route::get('/users/pagination/fetch_data', 'UserController@fetchData')->name('users.fetch_data');
    Route::group(['prefix' => 'tasks'], function () {
        Route::post('change_status/{id}', 'TaskController@changeStatus')->name('task.status');
        Route::post('content/{id}', 'TaskController@updateContent')->name('task.content');
        Route::get('pagination/fetch_data', 'TaskController@fetchData')->name('tasks.fetch_data');
        Route::get('/charts', 'TaskController@doChart')->middleware('permission:edit-user|delete-user');
    });
    Route::resource('tasks', 'TaskController');
    Route::resource('statuses', 'StatusController');
    Route::resource('categories', 'CategoryController');
    Route::get('/categories/pagination/fetch_data', 'CategoryController@fetchData')->name('category.fetchData');
});
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Backend/API/TaskController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskAddRequest;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Task;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        return response()->json([
            'statusCode'    =>  200,
            'data'          =>  $tasks
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskAddRequest $request)
    {
        //add task
        $task = new Task;
        $task->name = $request->task_name;
        $task->statusid = $request->status;
        $task->save();

        // add staff of that task
        $mang=array();
        foreach ($request->user as $value) {
            $mang[]=$value;
        }
        $task->user()->Attach($mang);

        return response()->json([
            'status'    =>  'success',
            'message'   =>  'Thêm công việc thành công'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $task
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/API/UserController.php
<?php

namespace App\Http\Controllers\Backend\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Http\Response;
use App\Http\Requests\{UserAddRequest,UserEditRequest};

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function index()
    {
        $users = User::all();
        return response()->json([
            'status' => '200',
            'data'   => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return Response
     */
    public function store(UserAddRequest $request)
    {
        $request_data = $request->all();
        $request_data['password'] = bcrypt($request->input['password']);
        return User::create($request_data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = User::findorFail($id);
        return response()->json([
                'status'    =>  200,
                'message'   =>  'success',
                'data'      =>  $user
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findorfail($id);
        $request_data = $request->all();
        if(isset($request_data['password'])){
            $request_data['password'] = ($request_data['password']=="")?$user->password:bcrypt($request->input('password'));
        }
        $user->update($request_data);
        return response()->json([
            'status'    => 200,
            'message'   => 'Update user successfully',
            'data'      =>  $user
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json([
            'status'    =>  204,
            'message'   =>  'Delete user successfully'
        ]);
    }
}

app/Http/Controllers/Backend/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\{CategoryAddRequest, CategoryEditRequest};
use Illuminate\View\View;

class CategoryController extends Controller
{
    protected $category;

    /**
     * CategoryController constructor.
     * @param $category
     */
    public function __construct(Category $category)
    {
        $this->category = $category;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryAddRequest $request
     * @return JsonResponse
     */
    public function store(CategoryAddRequest $request)
    {
        $requestData = $request->all();
        $this->category->saveCategory($requestData);
        return response()->json([
            'message' => 'Thêm danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $category = $this->category->findOrFail($id);
        return view('backend.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryEditRequest $request
     * @param int $id
     * @return JsonResponse
     */
    public function update(CategoryEditRequest $request, $id)
    {
        $requestData = $request->all();
        $this->category->updateCategory($requestData, $id);
        return response()->json([
            'message' => 'Sửa danh mục thành công',
            'data' => $this->reloadCategory()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     */
    public function destroy($id)
    {
        $category = $this->category->deleteCategory($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $category->id
        ]);
    }

    public function fetchData(Request $request)
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }

    public function reloadCategory()
    {
        $categories = $this->category->getPaginate(6);
        return view('backend.category.data_body', compact('categories'))->render();
    }
}

app/Http/Controllers/Backend/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index(){
        return view('backend.index');
    }
}

app/Http/Controllers/Backend/Admin/StatusController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class StatusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return void
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return void
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Backend\Admin;

use App\Http\Controllers\Controller;
use App\Models\Status;
use App\Models\Task;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\View\View;
use App\Http\Requests\{TaskAddRequest, TaskEditRequest};
use Illuminate\Support\Facades\Auth;
use Throwable;

class TaskController extends Controller
{
    protected $user;
    protected $task;
    protected $status;

    /**
     * TaskController constructor.
     * @param Task $task
     * @param User $user
     * @param Status $status
     */
    public function __construct(Task $task, User $user, Status $status)
    {
        $this->task = $task;
        $this->user = $user;
        $this->status = $status;
    }

    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.index', compact('users', 'tasks', 'status'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return void
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param TaskAddRequest $request
     * @return array|string
     * @throws Throwable
     */
    public function store(TaskAddRequest $request)
    {
        $requestData = $request->all();
        $task = $this->task->saveTask($requestData);
        return response()->json([
            'urlTask' => route('tasks.show', $task->id),
            'message' => 'Thêm công việc thành công',
            'data' => $this->reloadTask()
        ]);

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $task = $this->task->findOrFail($id);
        return view('backend.task.content', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $task = $this->task->findOrFail($id);
        $status = $this->status->all();
        $users = $this->user->getAll();
        return view('backend.task.edit', compact('users', 'task', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param TaskEditRequest $request
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function update(TaskEditRequest $request, $id)
    {
        $requestData = $request->all();
        $task = $this->task->updateTask($requestData, $id);
        return response()->json([
            'id' => $task->id,
            'message' => 'Cập nhật công việc thành công',
            'data' => $this->reloadTask(),
            'urlTask' => route('tasks.show', $task->id)
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return mixed
     * @throws Throwable
     */
    public function updateContent(Request $request, $id)
    {
        $this->task->updateContent($request->all(), $id);
        return response()->json([
            'message' => 'Cập nhật thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return array|string
     * @throws Throwable
     */
    public function destroy($id)
    {
        $task = $this->task->deleteTask($id);
        return response()->json([
            'message' => 'Xóa thành công',
            'id' => $task->id
        ]);
    }

    /**
     * @param Request $request
     * @param $id
     * @return array|string
     * @throws Throwable
     */
    public function changeStatus(Request $request, $id)
    {
        $requestData = $request->all();
        $this->task->changeStatus($requestData, $id);
        return response()->json([
            'message' => 'Cập nhật trạng thái thành công',
            'data' => $this->reloadTask()
        ]);
    }

    /**
     * @param Request $request
     * @return array|string
     * @throws Throwable
     */
    public function fetchData(Request $request)
    {
        $users = $this->user->getAll();
        $status = $this->status->all();
        $txtSearch = str_replace(" ", "%", $request->get('txtSearch'));
        $tasks = $this->task->getTaskByQuery($txtSearch, 5);
        if ($tasks->count() > 0) {
            return view('backend.task.data_body', compact('users', 'status', 'tasks'))->render();
        } else {
            return "Không tìm thấy kết quả";
        }
    }

    /**
     * @return Application|Factory|View
     */
    public function doChart()
    {
        return view('backend.task.chart');
    }

    /**
     * @return array|string
     * @throws Throwable
     */
    public function reloadTask()
    {
        $users = $this->user->getAll();
        $userId = Auth::user()->id;
        $tasks = $this->user->getTaskByUser($userId, 5);
        $status = $this->status->all();
        return view('backend.task.data_body', compact('users', 'tasks', 'status'))->render();
    }
}

resources/views/backend/user/data_body.blade.php
@foreach($users as $user)
    <tr id="user{{$user->id}}">
        <td>#{{$user->id}}</td>
        <td>{{$user->name}}</td>
        <td>
            @if($user->image!= "")
                <div class='user-profile'><img class="avatar-image" src='images/users/{{$user->image}}' alt=''
                                               title="{{$user->name}}"></div>
            @else
                <div class='user-profile'><img class="avatar-image" src='images/users/user.png' alt=''
                                               title="{{$user->name}}"></div>
            @endif
        </td>
        <td>{{$user->email}}</td>
        <td>{{$user->address}}</td>
        <td>{{$user->phone}}</td>
        <td>
            @foreach($user->roles as $role)
                <label class="badge badge-success">{{ $role->name }}</label>
            @endforeach
        </td>
        <td>
            <button type="button" data-info='@json($user)' name="edit" id="{{$user->id}}"
                    class="edit btn btn-primary btn-sm" data-toggle="modal"
                    data-target="#editUserModal" data-action="{{route('users.edit',$user->id)}}" title="Sửa">Sửa
            </button>
            <button type="button" name="delete" id="{{$user->id}}" class="delete btn btn-danger btn-sm"
                    data-action="{{ route('users.destroy',$user->id) }}" title="Xóa">Xóa
            </button>
        </td>
    </tr>
@endforeach
<tr>
    <td colspan="8">
        {{$users->links()}}
    </td>
</tr>

resources/views/backend/user/edit.blade.php
<div class="modal-header">
    <h5 class="modal-title" id="titleLabel">Sửa nhân viên</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form action="{{ route('users.update',$user->id) }}" method="post" id="editUserForm" class="form-horizontal"
      enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <span id="form_result"></span>
    <div class="modal-body">
        <div class="form-group">
            <div class="row">
                <label for="name" class="control-label col-md-4">Họ tên</label>
                <input type="text" class="form-control col-md-8" id="name" name="name" value="{{$user->name}}"/>
            </div>

        </div>
        <div class="form-group">
            <div class="row">
                <label for="email" class="control-label col-md-4">Email</label>
                <input type="email" class="form-control col-md-8" id="email" name="email" value="{{$user->email}}" autocomplete="current-email" />
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label for="image" class="control-label col-md-4">Ảnh đại diện</label>
                <div class="col-md-8">
                    <input type="file" id="image" name="image"/>
                    <img src="images/users/@if($user->image!=""){{$user->image}}@else{{"user.png"}}@endif"
                         id="avt_image" class="img-thumbnail"/>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label for="password" class="control-label col-md-4">Password</label>
                <input type="password" class="form-control col-md-8" id="password" name="password" autocomplete="current-password" />
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label for="address" class="control-label col-md-4">Địa chỉ</label>
                <input type="text" class="form-control col-md-8" id="address" name="address"
                       value="{{$user->address}}"/>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label for="phone" class="control-label col-md-4">Số điện thoại</label>
                <input type="text" class="form-control col-md-8" id="phone" name="phone" value="{{$user->phone}}"/>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <label for="role" class="control-label col-md-4">Chức vụ</label>
                @foreach($roles as $role)
                    <label style="margin-right: 12px">
                        <input type="checkbox" value="{{ $role->id }}"
                               @foreach($roleByUser as $item)
                               @if($role->id == $item)
                               {{"checked"}}
                               @endif
                               @endforeach
                               name="role[]" id="role_{{$role->id}}"
                               style="vertical-align: middle;margin-right: 2px"/>{{ $role->name }}
                    </label>
                @endforeach
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <input type="hidden" name="hidden_id" value="{{$user->id}}">
        <input type="submit" name="btn_update_user" id="btn_update_user" class="btn btn-success"
               value="Lưu lại" data-action="{{ route('users.update',$user->id) }}"/>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
    </div>
</form>

resources/views/backend/user/index.blade.php
@extends('backend.master.master')
@section('title','User Management')
@section('content')
    <div class="container">
        <br/>
        <div align="right">
            <button type="button" name="add_user" id="add_user" class="btn btn-success" data-toggle="modal"
                    data-target="#userModal">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                Thêm
            </button>
        </div>
        <div class="row">
            <form data-action="{{ route('users.fetch_data') }}" method="get" id="fetchDataForm"
                  style="width: 100%">
                <input class="col-md-4" type="text" name="txt_search" id="txt_search"
                       style="float: right;border-radius: 5px;padding: 5px;" placeholder="Tìm kiếm....">
            </form>

        </div>
        <br/>
        <div class="panel panel-default">
            <div class="panel-heading">Danh sách nhân viên</div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" id="user_table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Họ tên</th>
                            <th>Avatar</th>
                            <th>Email</th>
                            <th>Địa chỉ</th>
                            <th>Số điện thoại</th>
                            <th>Chức vụ</th>
                            <th>Hành động</th>
                        </tr>
                        </thead>
                        <tbody>
                        @include('backend.user.data_body')
                        </tbody>
                    </table>
                    <input type="hidden" name="hidden_page" id="hidden_page" value="1"/>
                </div>
                <br/>
                <br/>
            </div>
        </div>

        <!-- Add User Modal -->
        <div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="titleLabel">Thêm nhân viên</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="" method="post" id="userForm" class="form-horizontal" enctype="multipart/form-data">
                        @csrf
                        <span id="form_result"></span>
                        <div class="modal-body">
                            <div class="form-group">
                                <div class="row">
                                    <label for="name" class="control-label col-md-4">Họ tên</label>
                                    <input type="text" class="form-control col-md-8" id="name" name="name"/>
                                </div>

                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="email" class="control-label col-md-4">Email</label>
                                    <input type="email" class="form-control col-md-8" id="email" name="email" autocomplete="current-email"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="image" class="control-label col-md-4">Ảnh đại diện</label>
                                    <div class="col-md-8">
                                        <input type="file" id="image" name="image"/>
                                        <img src="images/users/user.png" id="avt_image" class="img-thumbnail"/>
                                    </div>

                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="password" class="control-label col-md-4">Password</label>
                                    <input type="password" class="form-control col-md-8" id="password" name="password" autocomplete="current-password" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="address" class="control-label col-md-4">Địa chỉ</label>
                                    <input type="text" class="form-control col-md-8" id="address" name="address"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="phone" class="control-label col-md-4">Số điện thoại</label>
                                    <input type="text" class="form-control col-md-8" id="phone" name="phone"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <label for="role" class="control-label col-md-4">Chức vụ</label>
                                    @foreach($roles as $role)
                                        <label style="margin-right: 12px"><input type="checkbox" value="{{ $role->id }}"
                                                                                 name="role[]" id="role_{{$role->id}}"
                                                                                 style="vertical-align: middle;margin-right: 2px"/>{{ $role->name }}
                                        </label>
                                    @endforeach
                                    <br/>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <input type="submit" name="btn_add_user" id="btn_add_user" class="btn btn-success"
                                   value="Lưu lại" data-action="{{route('users.store')}}"/>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!--Edit Modal-->
        <div class="modal fade" id="editUserModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">

                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    @parent
    <script src="js/backend/ajax/user.js"></script>
@endsection